openapi: 3.1.0
info:
  title: foodDoc
  version: 1.0.0
servers:
  - url: http://localhost:3010/
paths:
  /login:
    post:
      summary: ログイン
      operationId: authLogin
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
                  format: password
                  minLength: 8
              required:
                - email
                - password
      responses:
        "200":
          description: ログイン成功
        "401":
          description: 認証エラー
