prism:
  host: localhost
  port: 4010
  debug: true
  multiplex: true
  mock: true
  preview: false
  validateRequest: true
  errors:
    debug: false
  scenarios:
    default:
      # Default scenario for unmatched requests
      - name: Default Scenario
        request:
          method: GET
          path: /product/{productId}/base
        response:
          status: 400
          headers:
            Content-Type: "application/json"
          body:
            message: "Invalid Request"
    sample1:
      # Scenario for sample1 response
      - name: Sample 1 Scenario
        request:
          method: GET
          path: /product/1/base
        response:
          status: 200
          headers:
            Content-Type: "application/json"
          body:
            product_name: "Product 1"
            common_products_code: "ABC123"
            brand_name: "Brand 1"
            applying_date: "2023-01-01"
            maker_name: "Maker 1"
            pb_nb_classification: "PB"
    sample2:
      # Scenario for sample2 response
      - name: Sample 2 Scenario
        request:
          method: GET
          path: /product/2/base
        response:
          status: 200
          headers:
            Content-Type: "application/json"
          body:
            product_name: "Product 2"
            common_products_code: "XYZ789"
            brand_name: "Brand 2"
            applying_date: "2023-02-01"
            maker_name: "Maker 2"
            pb_nb_classification: "NB"
    sample3:
      # Scenario for sample3 response
      - name: Sample 3 Scenario
        request:
          method: GET
          path: /product/3/base
        response:
          status: 200
          headers:
            Content-Type: "application/json"
          body:
            product_name: "Product 3"
            common_products_code: "DEF456"
            brand_name: "Brand 3"
            applying_date: "2023-03-01"
            maker_name: "Maker 3"
            pb_nb_classification: "PB"
    sample4:
      # Scenario for sample4 response
      - name: Sample 4 Scenario
        request:
          method: GET
          path: /product/4/base
        response:
          status: 200
          headers:
            Content-Type: "application/json"
          body:
            product_name: "Product 4"
            common_products_code: "GHI789"
            brand_name: "Brand 4"
            applying_date: "2023-04-01"
            maker_name: "Maker 4"
            pb_nb_classification: "NB"
    sample5:
      # Scenario for sample5 response
      - name: Sample 5 Scenario
        request:
          method: GET
          path: /product/5/base
        response:
          status: 200
          headers:
            Content-Type: "application/json"
          body:
            product_name: "Product 5"
            common_products_code: "JKL012"
            brand_name: "Brand 5"
            applying_date: "2023-05-01"
            maker_name: "Maker 5"
            pb_nb_classification: "PB"
    sample6:
      # Scenario for sample6 response
      - name: Sample 6 Scenario
        request:
          method: GET
          path: /product/6/base
        response:
          status: 200
          headers:
            Content-Type: "application/json"
          body:
            product_name: "Product 6"
            common_products_code: "MNO345"
            brand_name: "Brand 6"
            applying_date: "2023-06-01"
            maker_name: "Maker 6"
            pb_nb_classification: "NB"
    sample7:
      # Scenario for sample7 response
      - name: Sample 7 Scenario
        request:
          method: GET
          path: /product/7/base
        response:
          status: 200
          headers:
            Content-Type: "application/json"
          body:
            product_name: "Product 7"
            common_products_code: "PQR678"
            brand_name: "Brand 7"
            applying_date: "2023-07-01"
            maker_name: "Maker 7"
            pb_nb_classification: "PB"
    sample8:
      # Scenario for sample8 response
      - name: Sample 8 Scenario
        request:
          method: GET
          path: /product/8/base
        response:
          status: 200
          headers:
            Content-Type: "application/json"
          body:
            product_name: "Product 8"
            common_products_code: "STU901"
            brand_name: "Brand 8"
            applying_date: "2023-08-01"
            maker_name: "Maker 8"
            pb_nb_classification: "NB"
    sample9:
      # Scenario for sample9 response
      - name: Sample 9 Scenario
        request:
          method: GET
          path: /product/9/base
        response:
          status: 200
          headers:
            Content-Type: "application/json"
          body:
            product_name: "Product 9"
            common_products_code: "VWX234"
            brand_name: "Brand 9"
            applying_date: "2023-09-01"
            maker_name: "Maker 9"
            pb_nb_classification: "PB"
    sample10:
      # Scenario for sample10 response
      - name: Sample 10 Scenario
        request:
          method: GET
          path: /product/10/base
        response:
          status: 200
          headers:
            Content-Type: "application/json"
          body:
            product_name: "Product 10"
            common_products_code: "YZA567"
            brand_name: "Brand 10"
            applying_date: "2023-10-01"
            maker_name: "Maker 10"
            pb_nb_classification: "NB"
    sample11:
      # Scenario for sample11 response
      - name: Sample 11 Scenario
        request:
          method: GET
          path: /product/11/base
        response:
          status: 200
          headers:
            Content-Type: "application/json"
          body:
            product_name: "Product 11"
            common_products_code: "BCD890"
            brand_name: "Brand 11"
            applying_date: "2023-11-01"
            maker_name: "Maker 11"
            pb_nb_classification: "PB"
    sample12:
      # Scenario for sample12 response
      - name: Sample 12 Scenario
        request:
          method: GET
          path: /product/12/base
        response:
          status: 200
          headers:
            Content-Type: "application/json"
          body:
            product_name: "Product 12"
            common_products_code: "EFG123"
            brand_name: "Brand 12"
            applying_date: "2023-12-01"
            maker_name: "Maker 12"
            pb_nb_classification: "NB"
    sample13:
      # Scenario for sample13 response
      - name: Sample 13 Scenario
        request:
          method: GET
          path: /product/13/base
        response:
          status: 200
          headers:
            Content-Type: "application/json"
          body:
            product_name: "Product 13"
            common_products_code: "HIJ456"
            brand_name: "Brand 13"
            applying_date: "2024-01-01"
            maker_name: "Maker 13"
            pb_nb_classification: "PB"
    sample14:
      # Scenario for sample14 response
      - name: Sample 14 Scenario
        request:
          method: GET
          path: /product/14/base
        response:
          status: 200
          headers:
            Content-Type: "application/json"
          body:
            product_name: "Product 14"
            common_products_code: "KLM789"
            brand_name: "Brand 14"
            applying_date: "2024-02-01"
            maker_name: "Maker 14"
            pb_nb_classification: "NB"
    sample15:
      # Scenario for sample15 response
      - name: Sample 15 Scenario
        request:
          method: GET
          path: /product/15/base
        response:
          status: 200
          headers:
            Content-Type: "application/json"
          body:
            product_name: "Product 15"
            common_products_code: "NOP012"
            brand_name: "Brand 15"
            applying_date: "2024-03-01"
            maker_name: "Maker 15"
            pb_nb_classification: "PB"
    sample16:
      # Scenario for sample16 response
      - name: Sample 16 Scenario
        request:
          method: GET
          path: /product/16/base
        response:
          status: 200
          headers:
            Content-Type: "application/json"
          body:
            product_name: "Product 16"
            common_products_code: "QRS345"
            brand_name: "Brand 16"
            applying_date: "2024-04-01"
            maker_name: "Maker 16"
            pb_nb_classification: "NB"
    sample17:
      # Scenario for sample17 response
      - name: Sample 17 Scenario
        request:
          method: GET
          path: /product/17/base
        response:
          status: 200
          headers:
            Content-Type: "application/json"
          body:
            product_name: "Product 17"
            common_products_code: "TUV678"
            brand_name: "Brand 17"
            applying_date: "2024-05-01"
            maker_name: "Maker 17"
            pb_nb_classification: "PB"
    sample18:
      # Scenario for sample18 response
      - name: Sample 18 Scenario
        request:
          method: GET
          path: /product/18/base
        response:
          status: 200
          headers:
            Content-Type: "application/json"
          body:
            product_name: "Product 18"
            common_products_code: "WXY901"
            brand_name: "Brand 18"
            applying_date: "2024-06-01"
            maker_name: "Maker 18"
            pb_nb_classification: "NB"
    sample19:
      # Scenario for sample19 response
      - name: Sample 19 Scenario
        request:
          method: GET
          path: /product/19/base
        response:
          status: 200
          headers:
            Content-Type: "application/json"
          body:
            product_name: "Product 19"
            common_products_code: "ZAB234"
            brand_name: "Brand 19"
            applying_date: "2024-07-01"
            maker_name: "Maker 19"
            pb_nb_classification: "PB"
    sample20:
      # Scenario for sample20 response
      - name: Sample 20 Scenario
        request:
          method: GET
          path: /product/20/base
        response:
          status: 200
          headers:
            Content-Type: "application/json"
          body:
            product_name: "Product 20"
            common_products_code: "CDE567"
            brand_name: "Brand 20"
            applying_date: "2024-08-01"
            maker_name: "Maker 20"
            pb_nb_classification: "NB"
